=== Alexisjuarez34/microsoft-teams-library-js/packages/teams-js/tools/capabilityJson/schemas/capability.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/Capability",
  "type": "object",
  "title": "TeamsJS Capability Schema",
  "description": "Schema for a TeamsJS capability",
  "properties": {
    "capabilityName": {
      "$comment": "This is the name of the capability. It must be unique and is used to generate the capability's namespace which is referenced by consumers of the TeamsJS Library.",
      "type": "string",
      "minLength": 3,
      "maxLength": 30
    },
    "comment": {
      "$comment": "This should be a brief description of the capability, what developers use it for, and how it works.",
      "type": "string",
      "minLength": 15,
      "maxLength": 1000
    },
    "beta": {
      "$comment": "This is a boolean value that indicates whether the capability is in beta. If true, the capability will be hidden from the public documentation and can be freely changed. If false, the capability can only be changed in non-breaking ways.",
      "type": "boolean"
    },
    "requiresDevicePermissions": {
      "$comment": "This is a boolean value that indicates whether the capability requires device permissions. If true, the capability will have code generated that allows developers to request and check the permissions associated with this capability.",
      "type": "boolean"
    },
    "exportedInterfaces": {
      "$comment": "This is an array of objects that represent the interfaces that are exported by this capability. These interfaces are used by the capability's consumers to interact with the capability and can be passed into and returned from the capability's functions",
      "type": "array",
      "items": { "$ref": "/ExportedInterface" },
      "minItems": 1,
      "uniqueItems": true
    },
    "exportedReturnFunctions": {
      "$comment": "This is an array of objects that represent functions that consumers of your capability can call. These functions will send some data to the host and return a `Promise`. Developers can `await` that `Promise`; when the `Promise` resolves the call has been completed successfully and any data returned as a result of the call can be retrieved.",
      "type": "array",
      "items": { "$ref": "/ExportedReturnFunction" },
      "minItems": 1,
      "uniqueItems": true
    },
    "exportedFireAndForgetFunctions": {
      "$comment": "This is an array of objects that represent functions that pass data to the host and receive nothing in return",
      "type": "array",
      "items": { "$ref": "/ExportedFireAndForgetFunction" },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": ["capabilityName", "comment", "beta"]
}

=== Alexisjuarez34/microsoft-teams-library-js/packages/teams-js/tools/capabilityJson/geoLocation.json
{
    "capabilityName": "geoLocation2",
    "comment": "Namespace to interact with the geoLocation module-specific part of the SDK. This is the newer version of location module.",
    "beta": true,
    "requiresDevicePermissions": true,
    "exportedInterfaces": [
        {
            "name": "Location",
            "comment": "Data struture to represent the location information",
            "members": [
                {
                    "name": "latitude",
                    "type": "number",
                    "comment": "Latitude of the location"
                },
                {
                    "name": "longitude",
                    "type": "number",
                    "comment": "Longitude of the location"
                },
                {
                    "name": "accuracy",
                    "type": "number",
                    "comment": "Accuracy describes the maximum distance in meters from the captured coordinates to the possible actual location",
                    "optional": true,
                    "remark": "This property is only in scope for mobile"
                },
                {
                    "name": "timestamp",
                    "type": "number",
                    "optional": true,
                    "comment": "Time stamp when the location was captured"
                }
            ]
        }
    ],
    "exportedReturnFunctions": [
        {
            "name": "getCurrentLocation",
            "returns": "Location",
            "returnComment": "A promise that resolves with the location of the user",
            "limitedToFrameContexts": [{"frameContext":"content"}, {"frameContext": "task"}],
            "requiredParameters": [
                {
                    "name": "foo",
                    "objectType": {
                        "typeName": "Location"
                    },
                    "comment": "Bar!"
                }
            ],
            "dataForHost": [{"basic": 1}, {"string": "hello"}, {"basic": "true"}, {"reference": "foo"}],
            "dataFromHost": [
                {
                    "name": "wasSuccessful",
                    "successCheck": true,
                    "errorMessage": "Call failed on host with generic error, please read our docs for more info"
                },
                {
                    "name": "err",
                    "sdkError": true
                },
                {
                    "name": "location",
                    "type": "Location",
                    "requiredForSuccess": true,
                    "errorMessage": "No location received from host",
                    "returnValue": true
                }
            ]
        }
    ]
}

=== Alexisjuarez34/microsoft-teams-library-js/packages/teams-js/tools/capabilityJson/fhl.json
{
  "capabilityName": "fhl",
  "comment": "This capability can be used to demonstrate how auto-generated code can be added to the SDk when developers are proposing new capabilities.",
  "beta": true,
  "exportedInterfaces": [
    {
      "name": "MySpecialInterface",
      "comment": "This is a simple object that we will pass back to the developer as a result of calling one of the functions",
      "members": [
        {
          "name": "hostReturnedNumber",
          "type": "number",
          "comment": "This is just any number at all that the host wanted the caller to have"
        },
        {
          "name": "specialHostString",
          "type": "string",
          "comment": "A special message the host would like to share with the caller!?"
        }
      ]
    }
  ],
  "exportedReturnFunctions": [
    {
      "name": "askHostForSpecialInterface",
      "returns": "MySpecialInterface",
      "comment": "Retrieve an updated Baz from the host",
      "returnComment": "A promise that resolves with the location of the user",
      "limitedToFrameContexts": [{ "frameContext": "content" }, { "frameContext": "task" }],
      "requiredParameters": [
        {
          "name": "appId",
          "uuidType": true,
          "comment": "The id that uniquely identifies your application"
        }
      ],
      "optionalParameters": [
        {
          "name": "isEnthusiastic",
          "booleanType": true,
          "comment": "Does the user want to be enthusiastic?"
        }
      ],
      "dataForHost": [
        {
          "name": "appId",
          "uuidType": true,
          "comment": "Unique application id",
          "reference": true
        },
        {
          "name": "isEnthusiastic",
          "booleanType": true,
          "comment": "Does the caller want to be enthusiastic?",
          "reference": true
        }
      ],
      "dataFromHost": {
        "errorName": "err",
        "returnValue": {
          "name": "specialInterfaceForYou",
          "type": "MySpecialInterface",
          "requiredForSuccess": true,
          "errorMessage": "No special interface received from host :(",
          "returnToCaller": true
        }
      }
    }
  ]
}
